dist: xenial
language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install isort flake8 yapf

script:
  - flake8
  - isort -rc --check-only --diff mmfashion/ tools/
  - yapf -r -d --style .style.yapf mmfashion/ tools/
